services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
    networks:
      - nginx-proxy-network

networks:
  nginx-proxy-network:
    name: nginx-proxy-network

volumes:
  data:
  letsencrypt:
